### ISSUE TITLE
Add support for Gopher Phlog's

### ISSUE THREAD

**Issue by vg** [estrabd/vee#43]
Since vee is allready available on freeshell.org, it would be nice if vee can also generate the gophermap and the raw txt files of the individual posts, such that they can be served over [Gopher](http://sdf.org/?tutorials/gopher) .

**Comment by estrabd** [comment]
@vg sorry for the extreme delay. I need to research this, but seems worth doing!  The raw text files are available in the .vee/*.raw (each post has a corresponding ".raw" file).

**Comment by estrabd** [comment]
@vg I am looking at old issues, can you provide me some informatino on generating gophermaps? E.g., what would they look like for vee posts?

**Comment by vg** [comment]
https://gopher.zone/posts/how-to-gophermap/
https://sdfeu.org/w/tutorials:gopher
https://dev.to/dotcomboom/the-gopher-protocol-in-brief-1d88

**Comment by estrabd** [comment]
Excellent, thank you!

**Comment by estrabd** [comment]
@vg I am working on this now that I understand what needs to be done; doesn't seem like too much work. Biggest issue is going to be  code organization.

`vee -G` to : 
* generate `.txt` instead of `.html` (or just both?)
* update `gopherlog` rather than index file (and also HTML index?)
* `vee-rebuild` to rebuild `gopherlog` based on `*.raw` files available

Let me know what you think. Do people maintain both gopher content and HTML content in the same directory?

**Comment by estrabd** [comment]
current status, see commit message for more info: 078760b6e4cf0f477e55c754fb0f

**Comment by estrabd** [comment]
Getting close, 6aae6ac1735e4dc25e5033acc471b31675bcc7ae:

```
* -g|-G seem to be working pretty good
* gophermap is rebuilt whenever -g|-G is used so that the latest posts appear first
* updated post management to fully utilize veels and veecat, need to test more

Overall lookin pretty good. Since this is a pretty disruptive change and took the
liberty to refactor a few things, this might end up being vee 2.0.
```

**Comment by estrabd** [comment]
@vg - kindly check out `master` at your convenience. The changes were great enough to make a full version jump. I tagged this `2.0-rc1` after testing it on SDF's gopher offers. I am very interested in your feedback. Thank you!
