### ISSUE TITLE
Which license?

### ISSUE THREAD

**Issue by balupton** [estrabd/vee#44]
Seems there is no license information in the form of a LICENSE file or a README note. Selecting one from https://spdx.org/licenses/ would be great.

**Comment by illandan** [comment]
A cursory search around this repo shows the owner preferring WTFPL.  It's recommended but not necessary to have a LICENSE file

**Comment by balupton** [comment]
@illandan can you give a link to back that up, as I can't find it - perhaps my searching skills suck

the reason why, is that we list all the static site generators on staticsitegenerators.net - and prefer to have definite source for licenses - in fact, if a license file is provided, then github even exposes the license information via their API, which makes consumption and verification a lot easier

**Comment by illandan** [comment]
@balupton here you go: https://github.com/estrabd/vee/search?utf8=✓&q=LICENSE

**Comment by balupton** [comment]
@illandan ah great! Didn't think of search, just looked in all the places the API looks.

Will set it to WTFPL on the ssg list
https://github.com/estrabd/vee/blob/2da33e731ef70edabe76b2345e71770b6ea4dd53/pod/vee.1.pod#license-and-copyright

**Comment by estrabd** [comment]
@balupton thanks for staticsitegenerators.net . Sorry for the extreme delay in this message. I created a LICENSE file and linked to your site in the README. It's funny there are so many SSGs and that they all  came to be around the same time (and mostly have since halted active development). Thanks for the input @illandan.
